name: Fix Invalid Filenames

on: [push]

jobs:
  fix-filenames:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Find and fix invalid filenames
      run: |
        set +e
        find . -type f | grep '[<>:："\\|?*]' > s-invalid.txt
        if [ -s s-invalid.txt ]; then
          cat s-invalid.txt | tr '<>:："\\|?*' '_' > s-fix.txt
          paste s-invalid.txt s-fix.txt | awk -F'\t' "{print \"mv -i -- '\\$1' '\\$2'\"}" > s-cmd.txt
          # Execute them (double-check before executing)
          # IMPORTANT: Commented out for safety. Review the commands before enabling this step.
        #   bash s-cmd.txt
          cat s-cmd.txt
        else
          echo "No invalid filenames found."
        fi
        set -e
      shell: /usr/bin/bash -e {0}
