name: Fix Invalid Filenames

on: [push]

jobs:
  fix-filenames:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Find and fix invalid filenames
      run: |
        find . -type f | grep '[<>:"\|?*]' > s-invalid.txt
        cat s-invalid.txt | tr '<>:"\|?*' '_' > s-fix.txt
        paste s-invalid.txt s-fix.txt | awk -F '[\t]' '{print "mv \047"\$1"\047 \047"\$2"\047"}' > s-cmd.txt
        # Execute them (double-check before executing)
        # IMPORTANT: Commented out for safety. Review the commands before enabling this step.
        # sh s-cmd.txt

    # Optional: Commit and push the changes to the repository
    - name: Commit and push if necessary
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Fix invalid filenames" || echo "No changes to commit"
        git push
