name: Rename Files

on: [push, pull_request]

jobs:
  rename-colons:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Find and replace ":" in file names
      run: |
        find . -type f -name "*:*" | while read fname; do
          # Replace ":" with "-" in the file name
          new_fname=$(echo $fname | tr ':' '-')
          mv -v "$fname" "$new_fname"
          echo "Renamed $fname to $new_fname"
        done

    - name: Commit and push if necessary
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -u
        git commit -m "Replace ':' with '-' in filenames" || echo "No changes to commit"
        git push
